--<ScriptOptions statementTerminator="GO"/>

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE AspNetUsers (
	Id INT NOT NULL,
	AccountType VARCHAR(2147483647),
	Email VARCHAR(256),
	EmailConfirmed BIT NOT NULL,
	PasswordHash VARCHAR(2147483647),
	SecurityStamp VARCHAR(2147483647),
	PhoneNumber VARCHAR(2147483647),
	PhoneNumberConfirmed BIT NOT NULL,
	TwoFactorEnabled BIT NOT NULL,
	LockoutEndDateUtc DATETIME,
	LockoutEnabled BIT NOT NULL,
	AccessFailedCount INT NOT NULL,
	UserName VARCHAR(256) NOT NULL,
	Type VARCHAR(2147483647),
	Category VARCHAR(2147483647),
	Name VARCHAR(2147483647),
	Photo VARCHAR(2147483647),
	Rating INT,
	Seniority VARCHAR(2147483647),
	Status VARCHAR(2147483647),
	Name1 VARCHAR(2147483647),
	IdProfile INT,
	Specialty VARCHAR(2147483647),
	Discriminator VARCHAR(128) NOT NULL,
	JobRequest_IdRequest INT,
	CONSTRAINT PK_dbo.AspNetUsers PRIMARY KEY (Id) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

CREATE INDEX IX_IdProfile ON AspNetUsers (IdProfile ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE UNIQUE INDEX UserNameIndex ON AspNetUsers (UserName ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE INDEX IX_JobRequest_IdRequest ON AspNetUsers (JobRequest_IdRequest ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

SET ANSI_PADDING OFF
GO

